name: Check

on:
  schedule:
    - cron: '0 12 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Test1
          echo Test2

      - name: Check
        run: |
          echo ${{ github.workspace }}
          echo ${{ GITHUB_WORKSPACE }}
      
      - name: Run the processor
        run: |
          chmod +x ${{ github.workspace }}/.github/process.sh
          ${{ github.workspace }}/.github/process.sh ${{ github.workspace }}/config.json
